language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

secure:
  # SCRUTINIZER_TOKEN
  - "UQMXhAqAKu89NQGz/cinWaJILL7SaIpWrrRxNRoVee6b4OJt+3vvkVNZUZguVmh2xEsJnFkL4ILrzYdRJ7eJL/tgb7fSPamcBirL3l5irL4m867a0jRCZrPMf9OChKw+RRXhHaMm9dd/G4BDbsanovwmx2vXDV26M7lC/uVeZh4="

services:
  - redis-server

install:
  # Install dependencies.
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
  - "pip install scrutinizer-ocular"

  # Start the server in the background. We don't acutally use this for tests but we
  # need to generate the LALR tables.
  - "bin/tesseract &"

  # Generate tests from YAML.
  - "python generate_tests.py"

# Run tests.
script: nosetests --with-coverage --cover-package=tesseract

# Submit code coverage data.
after_success:
  - coveralls
  - ocular --access-token "$SCRUTINIZER_TOKEN"
