language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

services:
  - redis-server

install:
  # Install dependencies.
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
  
  # Connecting to the server will generate LALR tables.
  - "python tesseract.py"
  
  # Generate tests from YAML.
  - "python generate_tests.py"

# Run tests.
script: nosetests --with-coverage --cover-package=tesseract

# Submit code coverage data.
after_success:
  coveralls
