language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

services:
  - redis-server

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
  - "python generate_tests.py"

# command to run tests
script: nosetests --with-coverage --cover-package=tesseract

after_success:
  coveralls
